# Vagrant conf.
Vagrant.configure("2") do |config|
  config.vm.box = "mntlab"
  config.vm.box_url = "mntlab20160711.box"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.provision "shell", path: "script.sh" 
end
